version: "3.8"

services:
  db:
    image: postgres:12
    container_name: test_system_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tashkent
      PGTZ: Asia/Tashkent
      POSTGRES_DB: test_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    networks:
#      - test_system_net
  redis:
    image: redis:alpine
    container_name: test_system_redis
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - "6379:6379"
#    networks:
#      - test_system_net
  web:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    container_name: test_system_django_admin_panel
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./admin_panel/.env
    depends_on:
      - db
#    networks:
#      - test_system_net
    command: >
      sh -c "python manage.py runserver 127.0.0.1:8000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: test_system_server
    restart: on-failure
    ports:
      - "8002:8002"
    env_file:
      - ./server/.env
    depends_on:
      - db
      - redis
#    networks:
#      - test_system_net
    command: >
      sh -c "python -m src.main createuploadsfile && python -m src.main"

volumes:
  postgres_data:
  redis_data:

#networks:
#  test_system_net:
#    external: true